// src/lib/feature-registry.ts
// Master index of every feature/page/module extracted from upstream repos.
// GENERATED BY Find Your King-HORUS Registry Script. DO NOT EDIT MANUALLY.

export type FeatureTag =
    | 'auth'
    | 'members-profiles'
    | 'likes-matching'
    | 'messaging'
    | 'presence'
    | 'events'
    | 'admin'
    | 'photo-upload'
    | 'p2p'
    | 'realtime'
    | 'billing'
    | 'email'
    | 'ai'
    | 'testing'
    | 'layout'
    | 'hooks'
    | 'db'
    | 'api'
    | 'config';

export interface Feature {
    repo: string;
    file: string;
    tags: FeatureTag[];
    exports: string[];
}

export const Features: Feature[] = [
    {
        repo: "findyourking-platform",
        file: "src/app/auth/login/page.tsx",
        tags: ["layout", "auth", "members-profiles", "likes-matching", "messaging", "events", "email", "ai"] as FeatureTag[],
        exports: ["LoginPage"],
    },
    {
        repo: "findyourking-platform",
        file: "src/app/auth/page.tsx",
        tags: ["layout", "auth", "members-profiles", "messaging", "events", "p2p", "email", "ai"] as FeatureTag[],
        exports: ["AuthPage"],
    },
    {
        repo: "findyourking-platform",
        file: "src/app/auth/register/page.tsx",
        tags: ["layout", "auth", "members-profiles", "likes-matching", "messaging", "events", "email", "ai"] as FeatureTag[],
        exports: ["RegisterPage"],
    },
    {
        repo: "findyourking-platform",
        file: "src/app/discover/page.tsx",
        tags: ["layout", "auth", "members-profiles", "likes-matching", "messaging", "presence", "photo-upload", "ai", "testing"] as FeatureTag[],
        exports: ["DiscoverPage"],
    },
    {
        repo: "findyourking-platform",
        file: "src/app/events/create/page.tsx",
        tags: ["layout", "auth", "members-profiles", "events", "photo-upload", "ai"] as FeatureTag[],
        exports: ["CreateEventPage"],
    },
    {
        repo: "findyourking-platform",
        file: "src/app/events/page.tsx",
        tags: ["layout", "auth", "members-profiles", "likes-matching", "events", "photo-upload", "ai", "testing"] as FeatureTag[],
        exports: ["EventsPage"],
    },
    {
        repo: "findyourking-platform",
        file: "src/app/layout.tsx",
        tags: ["layout", "auth", "members-profiles", "photo-upload", "p2p", "ai"] as FeatureTag[],
        exports: ["metadata", "RootLayout"],
    },
    {
        repo: "findyourking-platform",
        file: "src/app/live-location/page.tsx",
        tags: ["layout", "members-profiles", "messaging"] as FeatureTag[],
        exports: ["LiveLocationPage"],
    },
    {
        repo: "findyourking-platform",
        file: "src/app/matches/page.tsx",
        tags: ["layout", "members-profiles", "likes-matching", "messaging", "presence", "photo-upload", "ai"] as FeatureTag[],
        exports: ["MatchesPage"],
    },
    {
        repo: "findyourking-platform",
        file: "src/app/messages/page.tsx",
        tags: ["layout", "auth", "members-profiles", "likes-matching", "messaging", "presence", "events", "photo-upload", "ai"] as FeatureTag[],
        exports: ["MessagesPage"],
    },
    {
        repo: "findyourking-platform",
        file: "src/app/nearby/page.tsx",
        tags: ["layout", "auth", "members-profiles", "likes-matching", "messaging", "presence", "photo-upload", "ai"] as FeatureTag[],
        exports: ["NearbyPage"],
    },
    {
        repo: "findyourking-platform",
        file: "src/app/page.tsx",
        tags: ["layout", "auth", "ai", "db"] as FeatureTag[],
        exports: ["async"],
    },
    {
        repo: "findyourking-platform",
        file: "src/app/party-map/page.tsx",
        tags: ["layout", "members-profiles", "messaging", "presence", "events", "photo-upload", "ai", "testing"] as FeatureTag[],
        exports: ["PartyMapPage"],
    },
    {
        repo: "findyourking-platform",
        file: "src/app/profile/page.tsx",
        tags: ["layout", "auth", "members-profiles", "likes-matching", "events", "photo-upload", "email", "ai"] as FeatureTag[],
        exports: ["ProfilePage"],
    },
    {
        repo: "findyourking-platform",
        file: "src/app/settings/page.tsx",
        tags: ["layout", "auth", "members-profiles", "likes-matching", "messaging", "email", "ai"] as FeatureTag[],
        exports: ["SettingsPage"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/auth/AuthGuard.tsx",
        tags: ["layout", "auth", "members-profiles", "email", "ai"] as FeatureTag[],
        exports: ["AuthGuard", "withAuth"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/auth/LoginForm.tsx",
        tags: ["layout", "auth", "members-profiles", "events", "email", "ai", "testing"] as FeatureTag[],
        exports: ["LoginForm"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/auth/RegisterForm.tsx",
        tags: ["layout", "auth", "members-profiles", "likes-matching", "events", "email", "ai", "testing"] as FeatureTag[],
        exports: ["RegisterForm"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/coaching/AICoachingPanel.tsx",
        tags: ["layout", "auth", "members-profiles", "likes-matching", "messaging", "presence", "events", "photo-upload", "ai", "testing", "db"] as FeatureTag[],
        exports: ["AICoachingPanel"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/enterprise/DatingGrid.tsx",
        tags: ["layout", "members-profiles", "likes-matching", "messaging", "presence", "events", "photo-upload", "ai"] as FeatureTag[],
        exports: ["DatingGrid"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/enterprise/MessagingInterface.tsx",
        tags: ["layout", "auth", "members-profiles", "messaging", "presence", "events", "photo-upload", "p2p", "realtime", "ai"] as FeatureTag[],
        exports: ["MessagingInterface"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/enterprise/ProfileView.tsx",
        tags: ["layout", "auth", "members-profiles", "likes-matching", "messaging", "presence", "events", "photo-upload", "ai", "testing"] as FeatureTag[],
        exports: ["ProfileView"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/layout/BottomNav.tsx",
        tags: ["layout", "members-profiles", "messaging", "events"] as FeatureTag[],
        exports: ["BottomNav"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/layout/Navbar.tsx",
        tags: ["layout", "members-profiles", "likes-matching", "messaging", "events"] as FeatureTag[],
        exports: ["Navbar"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/layout/SearchBar.tsx",
        tags: ["layout", "members-profiles", "events", "photo-upload", "ai"] as FeatureTag[],
        exports: ["SearchBar"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/layout/Sidebar.tsx",
        tags: ["layout", "members-profiles", "likes-matching", "messaging", "events", "ai"] as FeatureTag[],
        exports: ["Sidebar"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/matching/FavoriteButton.tsx",
        tags: ["layout", "members-profiles", "likes-matching", "events"] as FeatureTag[],
        exports: ["FavoriteButton"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/matching/FilterPanel.tsx",
        tags: ["layout", "members-profiles", "likes-matching", "photo-upload"] as FeatureTag[],
        exports: ["FilterPanel"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/matching/MatchDetailsModal.tsx",
        tags: ["layout", "members-profiles", "likes-matching", "messaging", "presence", "photo-upload", "ai", "testing"] as FeatureTag[],
        exports: ["MatchDetailsModal"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/matching/ProfileCard.tsx",
        tags: ["layout", "members-profiles", "likes-matching", "messaging", "testing"] as FeatureTag[],
        exports: ["ProfileCard"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/matching/SwipeCard.tsx",
        tags: ["layout", "members-profiles", "likes-matching", "events", "photo-upload", "ai", "testing"] as FeatureTag[],
        exports: ["SwipeCard"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/messaging/ChatWindow.tsx",
        tags: ["layout", "members-profiles", "messaging", "events", "photo-upload"] as FeatureTag[],
        exports: ["ChatWindow"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/messaging/ConversationList.tsx",
        tags: ["layout", "members-profiles", "messaging", "testing"] as FeatureTag[],
        exports: ["ConversationList"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/messaging/MessageBubble.tsx",
        tags: ["layout", "members-profiles", "messaging", "photo-upload", "testing"] as FeatureTag[],
        exports: ["MessageBubble"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/messaging/MessageReactions.tsx",
        tags: ["layout", "messaging"] as FeatureTag[],
        exports: ["MessageReactions"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/messaging/TypingIndicator.tsx",
        tags: ["layout", "members-profiles"] as FeatureTag[],
        exports: ["TypingIndicator"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/profile/PhotoGallery.tsx",
        tags: ["layout", "members-profiles", "events", "photo-upload", "ai", "testing"] as FeatureTag[],
        exports: ["PhotoGallery"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/profile/ProfileDetail.tsx",
        tags: ["layout", "members-profiles", "likes-matching", "messaging", "photo-upload", "ai"] as FeatureTag[],
        exports: ["ProfileDetail"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/profile/ProfileEditor.tsx",
        tags: ["layout", "members-profiles", "photo-upload", "ai", "testing"] as FeatureTag[],
        exports: ["ProfileEditor"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/profile/VerificationBadge.tsx",
        tags: ["layout", "members-profiles", "photo-upload"] as FeatureTag[],
        exports: ["VerificationBadge"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/providers/auth-provider.tsx",
        tags: ["layout", "auth", "members-profiles", "events", "email", "ai", "db"] as FeatureTag[],
        exports: ["AuthProvider", "useAuth"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/providers/query-provider.tsx",
        tags: ["layout", "messaging", "ai"] as FeatureTag[],
        exports: ["QueryProvider"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/providers/theme-provider.tsx",
        tags: ["layout"] as FeatureTag[],
        exports: ["ThemeProvider"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/ui/badge.tsx",
        tags: ["layout", "auth"] as FeatureTag[],
        exports: ["BadgeProps"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/ui/button.tsx",
        tags: ["layout", "auth", "events"] as FeatureTag[],
        exports: ["ButtonProps"],
    },
    {
        repo: "findyourking-platform",
        file: "src/components/ui/input.tsx",
        tags: ["layout"] as FeatureTag[],
        exports: ["InputProps"],
    },
    {
        repo: "findyourking-platform",
        file: "src/hooks/use-auth.ts",
        tags: ["hooks", "auth", "members-profiles", "events", "email", "ai", "db"] as FeatureTag[],
        exports: ["useAuth"],
    },
    {
        repo: "findyourking-platform",
        file: "src/hooks/use-chat.ts",
        tags: ["hooks", "members-profiles", "messaging", "events", "realtime", "ai", "db"] as FeatureTag[],
        exports: ["useChat"],
    },
    {
        repo: "findyourking-platform",
        file: "src/hooks/use-discovery.ts",
        tags: ["hooks", "members-profiles", "likes-matching", "ai", "db"] as FeatureTag[],
        exports: ["useDiscovery"],
    },
    {
        repo: "findyourking-platform",
        file: "src/hooks/use-events.ts",
        tags: ["hooks", "members-profiles", "likes-matching", "events", "photo-upload", "ai", "db"] as FeatureTag[],
        exports: ["useEvents"],
    },
    {
        repo: "findyourking-platform",
        file: "src/hooks/use-notifications.ts",
        tags: ["hooks", "auth", "members-profiles", "ai"] as FeatureTag[],
        exports: ["useNotifications"],
    },
    {
        repo: "findyourking-platform",
        file: "src/hooks/use-online-status.ts",
        tags: ["hooks", "events"] as FeatureTag[],
        exports: ["useOnlineStatus"],
    },
    {
        repo: "findyourking-platform",
        file: "src/hooks/use-p2p.ts",
        tags: ["hooks", "members-profiles", "messaging", "events", "p2p", "ai", "testing"] as FeatureTag[],
        exports: ["useP2P"],
    },
    {
        repo: "findyourking-platform",
        file: "src/hooks/useDebounce.ts",
        tags: ["hooks", "members-profiles", "testing"] as FeatureTag[],
        exports: ["useDebounce"],
    },
    {
        repo: "findyourking-platform",
        file: "src/hooks/useGeolocation.ts",
        tags: ["hooks", "members-profiles", "messaging", "ai"] as FeatureTag[],
        exports: ["useGeolocation"],
    },
    {
        repo: "findyourking-platform",
        file: "src/hooks/useIntersectionObserver.ts",
        tags: ["hooks", "members-profiles", "photo-upload"] as FeatureTag[],
        exports: ["useIntersectionObserver"],
    },
    {
        repo: "findyourking-platform",
        file: "src/lib/ai/openrouter.ts",
        tags: ["config", "auth", "members-profiles", "likes-matching", "messaging", "ai", "testing"] as FeatureTag[],
        exports: ["OpenRouterError", "OpenRouterRateLimitError", "OpenRouterParseError", "OpenRouterConfig", "ChatMessage", "ChatCompletionOptions", "ChatCompletionResponse", "MatchingAnalysis", "ChatSuggestion", "createOpenRouterClient", "OpenRouterClient"],
    },
    {
        repo: "findyourking-platform",
        file: "src/lib/api/events.ts",
        tags: ["config", "auth", "events", "ai"] as FeatureTag[],
        exports: ["EventAPI"],
    },
    {
        repo: "findyourking-platform",
        file: "src/lib/api/live-location.ts",
        tags: ["config", "auth", "members-profiles", "ai"] as FeatureTag[],
        exports: ["LiveLocationAPI"],
    },
    {
        repo: "findyourking-platform",
        file: "src/lib/api/matches.ts",
        tags: ["config", "auth", "likes-matching", "messaging", "photo-upload", "ai"] as FeatureTag[],
        exports: ["MatchAPI"],
    },
    {
        repo: "findyourking-platform",
        file: "src/lib/api/settings.ts",
        tags: ["config", "auth", "ai"] as FeatureTag[],
        exports: ["SettingsAPI"],
    },
    {
        repo: "findyourking-platform",
        file: "src/lib/enterprise/HybridP2PDatingEngine.ts",
        tags: ["config", "auth", "members-profiles", "likes-matching", "messaging", "presence", "events", "photo-upload", "p2p", "realtime", "email", "ai", "db"] as FeatureTag[],
        exports: ["HybridEngineConfig", "EngineEvents", "HybridP2PDatingEngine"],
    },
    {
        repo: "findyourking-platform",
        file: "src/lib/enterprise/accessibility/AccessibilityManager.ts",
        tags: ["config", "likes-matching", "messaging", "events", "ai"] as FeatureTag[],
        exports: ["AccessibilityFeatures", "AccessibilityConfig", "AccessibilityManager", "getAccessibilityManager", "destroyAccessibilityManager"],
    },
    {
        repo: "findyourking-platform",
        file: "src/lib/enterprise/ai/AIMatchingEngine.ts",
        tags: ["config", "auth", "members-profiles", "likes-matching", "ai"] as FeatureTag[],
        exports: ["UserProfile", "CompatibilityScore", "MatchInsights", "AIMatchingEngine", "getAIMatchingEngine"],
    },
    {
        repo: "findyourking-platform",
        file: "src/lib/enterprise/encryption/ZeroKnowledgeEncryption.ts",
        tags: ["config", "messaging", "ai"] as FeatureTag[],
        exports: ["EncryptionConfig", "EncryptedMessage", "KeyPair", "KeyExchange", "ZeroKnowledgeEncryption", "getEncryption", "destroyEncryption"],
    },
    {
        repo: "findyourking-platform",
        file: "src/lib/enterprise/p2p/EnhancedSignalingStrategy.ts",
        tags: ["config", "messaging", "events", "p2p", "ai", "testing"] as FeatureTag[],
        exports: ["EnhancedSignalingStrategy"],
    },
    {
        repo: "findyourking-platform",
        file: "src/lib/enterprise/p2p/P2POptimizationManager.ts",
        tags: ["config", "p2p", "ai", "db"] as FeatureTag[],
        exports: ["P2POptimizationManager"],
    },
    {
        repo: "findyourking-platform",
        file: "src/lib/enterprise/p2p/SignalingStrategy.ts",
        tags: ["config", "members-profiles", "messaging", "events", "p2p", "realtime", "ai"] as FeatureTag[],
        exports: ["SignalingMethod", "SignalingConfig", "SignalingMessage", "ConnectionState", "SignalingStrategy", "getSignalingStrategy", "destroySignalingStrategy"],
    },
    {
        repo: "findyourking-platform",
        file: "src/lib/enterprise/performance/PerformanceMonitor.ts",
        tags: ["config", "events", "photo-upload", "realtime", "ai"] as FeatureTag[],
        exports: ["PerformanceMetrics", "PerformanceConfig", "PerformanceEntry", "PerformanceMonitor", "getPerformanceMonitor", "destroyPerformanceMonitor"],
    },
    {
        repo: "findyourking-platform",
        file: "src/lib/gps.ts",
        tags: ["config", "members-profiles", "ai"] as FeatureTag[],
        exports: ["calculateDistance", "formatDistance", "getCurrentPosition", "watchPosition", "clearWatch", "filterByDistance", "sortByDistance", "isWithinBounds", "getBoundingBox", "fuzzLocation"],
    },
    {
        repo: "findyourking-platform",
        file: "src/lib/p2p/engine.ts",
        tags: ["config", "members-profiles", "messaging", "events", "photo-upload", "p2p", "realtime", "ai", "testing"] as FeatureTag[],
        exports: ["P2PConfigSchema", "P2PConfig", "P2PMessageSchema", "P2PMessage", "P2PPeerSchema", "P2PPeer", "P2PCallConfigSchema", "P2PCallConfig", "FileTransferConfigSchema", "FileTransferConfig", "P2PEvents", "SignalingStrategy", "ConnectionMetrics", "EncryptionKeyPair", "FileTransferState", "P2PError", "P2PEncryptionError", "P2PConnectionError", "P2PFileTransferError", "P2PEngine", "getP2PEngine", "isP2PEngineAvailable", "getCurrentP2PEngine", "resetP2PEngine"],
    },
    {
        repo: "findyourking-platform",
        file: "src/lib/p2p/enhanced-enterprise-engine.ts",
        tags: ["config", "members-profiles", "messaging", "events", "p2p", "ai"] as FeatureTag[],
        exports: ["EnhancedEnterpriseP2PEngine"],
    },
    {
        repo: "findyourking-platform",
        file: "src/lib/p2p/enterprise-engine.ts",
        tags: ["config", "members-profiles", "likes-matching", "messaging", "events", "photo-upload", "p2p", "realtime", "ai", "testing"] as FeatureTag[],
        exports: ["P2PConfigSchema", "P2PConfig", "P2PMessageSchema", "P2PMessage", "P2PPeerSchema", "P2PPeer", "P2PCallConfigSchema", "P2PCallConfig", "FileTransferConfigSchema", "FileTransferConfig", "P2PEvents", "ConnectionMetrics", "AIInsight", "EncryptionKeyPair", "FileTransferState", "P2PError", "P2PEncryptionError", "P2PConnectionError", "P2PFileTransferError", "EnterpriseP2PEngine", "isP2PEngineAvailable", "getCurrentP2PEngine"],
    },
    {
        repo: "findyourking-platform",
        file: "src/lib/p2p-engine.ts",
        tags: ["config", "members-profiles", "messaging", "events", "p2p", "ai", "testing", "db"] as FeatureTag[],
        exports: ["P2PEngine", "getP2PEngine", "destroyP2PEngine"],
    },
    {
        repo: "findyourking-platform",
        file: "src/lib/schema.ts",
        tags: ["config", "auth", "members-profiles", "likes-matching", "messaging", "events", "photo-upload", "email", "ai"] as FeatureTag[],
        exports: ["loginSchema", "registerSchema", "resetPasswordSchema", "updatePasswordSchema", "profileSchema", "photoUploadSchema", "messageTypeSchema", "sendMessageSchema", "createConversationSchema", "eventCategorySchema", "createEventSchema", "updateEventSchema", "LoginInput", "RegisterInput", "ResetPasswordInput", "UpdatePasswordInput", "ProfileInput", "PhotoUploadInput", "SendMessageInput", "CreateConversationInput", "CreateEventInput", "UpdateEventInput", "EventCategory"],
    },
    {
        repo: "findyourking-platform",
        file: "src/lib/db/schema.ts",
        tags: ["config", "auth", "members-profiles", "likes-matching", "messaging", "events", "photo-upload", "email", "ai", "db"] as FeatureTag[],
        exports: ["User", "Profile", "Conversation", "Message", "AutoReplyRule", "VoiceCommand", "TranslationCache"],
    },
    {
        repo: "findyourking-platform",
        file: "src/lib/db/index.ts",
        tags: ["config", "auth", "members-profiles", "likes-matching", "messaging", "events", "photo-upload", "email", "ai", "db"] as FeatureTag[],
        exports: ["db", "redis", "cache", "sessions", "presence", "rateLimit"],
    },
    {
        repo: "findyourking-platform",
        file: "src/lib/utils.ts",
        tags: ["config", "photo-upload", "email", "ai", "testing"] as FeatureTag[],
        exports: ["cn", "formatDistance", "formatAge", "formatTimeAgo", "generateId", "validateEmail", "validatePassword", "truncateText", "debounce", "throttle", "getInitials", "sanitizeUrl", "isValidImageType", "compressImage"],
    },
    {
        repo: "findyourking-platform",
        file: "src/services/events.ts",
        tags: ["config", "members-profiles", "likes-matching", "events", "photo-upload", "ai", "db"] as FeatureTag[],
        exports: ["Event", "CreateEventInput", "UpdateEventInput", "EventFilters", "EventsService", "eventsService"],
    },
    {
        repo: "findyourking-platform",
        file: "src/services/messages.ts",
        tags: ["config", "members-profiles", "messaging", "events", "ai", "db"] as FeatureTag[],
        exports: ["ConversationWithLastMessage", "MessagesService", "messagesService"],
    },
    {
        repo: "findyourking-platform",
        file: "src/services/profiles.ts",
        tags: ["config", "members-profiles", "likes-matching", "ai", "db"] as FeatureTag[],
        exports: ["ProfileWithDistance", "ProfilesService", "profilesService"],
    },
    {
        repo: "findyourking-platform",
        file: "src/services/reports.ts",
        tags: ["config", "members-profiles", "messaging", "ai", "testing", "db"] as FeatureTag[],
        exports: ["ReportReason", "CreateReportInput", "ReportsService", "reportsService"],
    },
    {
        repo: "findyourking-platform",
        file: "src/store/app-store.ts",
        tags: ["auth", "members-profiles", "messaging", "photo-upload"] as FeatureTag[],
        exports: ["useAppStore", "useUser", "useIsAuthenticated", "useStage", "usePeers", "useChats", "useNotifications", "useFavorites", "useSearchFilters", "useSubscriptionTier", "useActiveCall", "useGpsEnabled", "useUserLocation"],
    },
    {
        repo: "findyourking-platform",
        file: "src/types/index.ts",
        tags: ["auth", "members-profiles", "likes-matching", "messaging", "events", "photo-upload", "email", "ai"] as FeatureTag[],
        exports: ["Location", "UserProfile", "PeerProfile", "Message", "Chat", "Notification", "SearchFilters", "SubscriptionTier", "AppStage"],
    },
    {
        repo: "findyourking-platform",
        file: "src/types/enterprise.ts",
        tags: ["auth", "members-profiles", "likes-matching", "messaging", "photo-upload", "p2p", "email", "ai", "config"] as FeatureTag[],
        exports: ["LocationData", "P2PConfig", "P2PMessage", "P2PCall", "UserProfile", "MatchScore", "SignalingStrategy", "AIAnalysis", "PerformanceMetrics", "AccessibilityFeatures", "SecuritySettings", "NotificationSettings", "EnterpriseConfig"],
    },
    {
        repo: "findyourking-platform",
        file: "src/types/events.ts",
        tags: ["members-profiles", "events", "photo-upload", "email", "ai", "db"] as FeatureTag[],
        exports: ["Event", "EventFilters"],
    },
    {
        repo: "findyourking-platform",
        file: "src/types/location.ts",
        tags: ["members-profiles", "messaging", "ai"] as FeatureTag[],
        exports: ["LocationData", "LocationSettings", "NearbyUser", "LocationRequest", "LocationHistory", "Geofence", "LocationAnalytics"],
    },
    {
        repo: "findyourking-platform",
        file: "src/types/matches.ts",
        tags: ["members-profiles", "likes-matching", "messaging", "photo-upload", "ai"] as FeatureTag[],
        exports: ["Match", "MatchFilters"],
    },
    {
        repo: "findyourking-platform",
        file: "src/types/settings.ts",
        tags: ["auth", "members-profiles", "likes-matching", "messaging", "events", "photo-upload", "billing", "email", "ai", "testing"] as FeatureTag[],
        exports: ["NotificationSettings", "PrivacySettings", "SecuritySettings", "AppearanceSettings", "PerformanceSettings", "AccountSettings"],
    }
];